### ISSUE TITLE
Занятие 3

### ISSUE THREAD

**Issue by dsokolov** [AltarixExercises2016/irbahtin.aleksandr#2]
1. Запуш проект целиком, чтобы можно было выкачать репозиторий и открыть проект в IDE. Сейчас в репе только 1 файл java, чтобы его запустить в среде разработки нужно создавать проект.

2. Фигурные скобки принято писать на той же строке, что и объявление класса. https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style Для форматирования в Идее и Студии есть хоткей ctrl+alt+L

3. Попробуй переделать следующим образом:
- ThisIsWrite работает пока работает приложение
- ThisIsRead убирает элемнеты из arr
- ThisIsRead работает пока есть элементы в arr. Когда закончились - приложение завершается.

**Comment by AleksandrIrb** [comment]
Запушил)

**Comment by dsokolov** [comment]
> ThisIsWrite работает пока работает приложение

вот это не сделано. В остальном ок.

**Comment by AleksandrIrb** [comment]
Запушил. Написал через while

**Comment by dsokolov** [comment]
Ok.
